/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 3, 2015 at 6:37:31 AM Central European Summer Time
* Operating System: Version 8.3 (Build 12F70)
* Image Source: /private/var/db/stash/_.2t7K5z/Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Cydia/Cydia-Structs.h>
#import <Cydia/PackageListController.h>

@interface FilteredPackageListController : PackageListController {

	Function<bool, Package *>* filter_;
	Function<void, NSMutableArray *>* sorter_;

}
-(id)_reloadPackages;
-(void)setSorter:(Function<void, NSMutableArray *>*)arg1 ;
-(id)initWithDatabase:(id)arg1 title:(id)arg2 filter:(Function<bool, Package *>*)arg3 ;
-(void)setFilter:(Function<bool, Package *>*)arg1 ;
@end

